data:
  test_size: 0.2
  random_state: 1

features:
  categorical_columns:
    - offline_listening
    - device_type
    - subscription_type
    - country
    - gender

model:
  name: random_forest
models:
  logistic_regression:
    C: 1.0
    max_iter: 200

  knn:
    n_neighbors: 5

  decision_tree:
    max_depth: 5

  random_forest:
    n_estimators: 100
    max_depth: 10

  svc:
    C: 1.0
    kernel: rbf
